name: Keep Render Alive Currency Converter

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Render app
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://currency-converter-i7w7.onrender.com/api/schema/swagger-ui/)
          echo "HTTP Status: $STATUS"
          if [[ "$STATUS" -ne 200 && "$STATUS" -ne 301 && "$STATUS" -ne 302 ]]; then
            echo "Ping failed with status $STATUS"
            exit 1
          fi

      - name: Send Email on Failure
        if: failure()  # Only run if previous step failed
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: danieligboke669@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Render App Ping Failed
          body: "Render Currency COnverter App is down! Go check."
          to: danieligboke669@gmail.com
          from: GitHub Actions
